### ISSUE TITLE
Frontend doesn't run due to incorrect package-lock.json

### ISSUE THREAD

**Issue by burgus7** [neha-deshpande001/PollBuddy#73]
Problem created here: https://github.com/neha-deshpande001/PollBuddy/commit/ecb7875423006e6103fdc08012cc0ed29dbbc676

package-lock.json created in root of repo, instead of using the existing file in the PollBuddy-Server/frontend folder where it should be. Causes frontend `npm start` to fail as it can't find the countdown module. 

Should just have to merge the files to fix. Probably worthwhile merging this into master asap, rather than waiting for the next frontend merge.

**Comment by hbh7** [comment]
Oh I fixed this
